services:
  mysql:
    image: mysql:5.7
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD:  root
      MYSQL_DATABASE: task_database
    ports:
      - "3306:3306"